/**
 * server/faceAlign.ts
 *
 * Where the host's face sits in a frame, so the split-screen crop can keep it.
 *
 * The split-screen host panel is the CANVAS REMAINDER, not a half: on 1920x1080 the b-roll
 * takes a square 1080 panel and the host gets 840. `buildSplitScreenArgs` cover-scales the
 * 1920x1080 lip-synced clip to fill that panel — which is a no-op, both are 1080 tall — and
 * then crops 840 wide. With no x that crop is CENTRED, so the panel is the middle 43.75% of
 * the source frame and everything outside it is discarded.
 *
 * That is fine only while the face is centred in the source. It frequently is not: the host
 * plate is generated by an image model from a photo reference (`hostPlate.ts`), and the model
 * frames the subject wherever it likes — off to one side, at the edge of the frame. The
 * lip-sync provider animates whatever it is handed, so an off-centre plate becomes an
 * off-centre clip, and the centred crop then pushes the face against the divider or slices it.
 *
 * So: look at a few frames, ask where the face is, pan the crop window to put it in the middle
 * of the panel — and then CHECK the panel (`verifyPanelFocus` in videoAssembly) rather than
 * trusting the estimate.
 *
 * Two detectors, tried in order:
 *   1. pico (`pico.ts`) — a real frontal-face cascade, pure JS, offline, deterministic, pixel
 *      precise. This is what does the work.
 *   2. Claude Haiku — only when pico finds no face (profile, heavy occlusion, stylised plate).
 *      Asked for the face's left/right EDGES, not a centre, which a vision model reads more
 *      honestly; still a coarse ruler, which is why the verify pass exists.
 *
 * NEVER THROWS. Every failure path — no key, a 529, an unparseable answer, no face in frame —
 * returns null, and null means "crop centred", which is exactly the behaviour that existed
 * before this module. A dead detector costs alignment, never a render.
 */
import sharp from "sharp";
import { invokeClaude, type ClaudeImage } from "./claude";
import { safeParseJSON } from "./jsonRepair";
import { detectFaces } from "./pico";

/** Which detector produced a reading. Logged and persisted so a bad crop can be traced. */
export type FaceSource = "pico" | "haiku";

/**
 * Haiku, for the same reason `overlayTextScan.ts` uses it: `invokeClaude` sends no `thinking`
 * param on its non-thinking branch, and on sonnet-5 that means ADAPTIVE THINKING — seconds of
 * reasoning per call, on the render's critical path, to locate a face. Haiku 4.5 predates
 * adaptive thinking, so this is a plain fast completion.
 */
const FACE_ALIGN_MODEL = "claude-haiku-4-5-20251001";

/**
 * Downscale before either detector. For Haiku, vision tokens are ~(w*h)/750, so the pixels
 * dominate the cost of a call this small. For pico, 640 wide keeps the dense multi-scale scan
 * under ~100 ms while a waist-up host's face is still 60-150 px — well inside the cascade's
 * comfortable range.
 */
const FACE_SCAN_WIDTH = 640;

const FACE_ALIGN_SYSTEM =
  "You are given ONE frame from a talking-head video. Locate the main person's FACE and " +
  "report its horizontal extent as fractions of the image width.\n\n" +
  "0.0 is the very left edge of the image, 0.5 is the exact horizontal middle, 1.0 is the " +
  "very right edge. Report the LEFT edge and RIGHT edge of the face itself — the skin of the " +
  "face from ear to ear — not the hair, not the shoulders, not the body.\n\n" +
  "If several people are visible, use the largest, most in-focus, most central face — the one " +
  "the shot is of. If no human face is visible at all, say so instead of guessing.\n\n" +
  'Return ONLY this JSON, no prose: {"found":true|false,"left":0.00,"right":0.00}\n' +
  "left/right: the fractions, 2 decimal places, left < right. Use 0.5 for both when found is false.";

/**
 * Read a verdict into a horizontal fraction, or null when there is nothing usable.
 *
 * Accepts the current `{left,right}` shape (centre is their midpoint) and the older bare `{x}`
 * shape. Null on anything off-shape, out of range, inverted, or not-found. The caller treats
 * null as "leave the crop centred", so a garbled answer must reach null rather than a
 * plausible-looking number — a confidently wrong 0.9 would pan the face straight out of the
 * panel, which is worse than the miscentring this module exists to fix.
 *
 * Pure — unit-tested.
 */
export function parseFaceCenter(
  raw: string,
  stopReason?: string
): number | null {
  const parsed = safeParseJSON<any>(raw, stopReason);
  if (!parsed.success) return null;
  const d = parsed.data;
  if (d?.found !== true) return null;
  const inUnit = (v: unknown): v is number =>
    typeof v === "number" && Number.isFinite(v) && v >= 0 && v <= 1;
  if (inUnit(d.left) && inUnit(d.right)) {
    if (d.right <= d.left) return null;
    return (d.left + d.right) / 2;
  }
  if (inUnit(d.x)) return d.x;
  return null;
}

/**
 * Median of the readings that came back, or null if none did.
 *
 * A median rather than a mean, and this is the whole point of sampling more than one frame: one
 * bad frame — a blink, motion blur, a dissolve, a hand across the face — produces one wild
 * reading, and a mean drags the crop toward it while a median ignores it outright. Two readings
 * average, which is the honest answer when there is no middle one to pick.
 *
 * Pure — unit-tested.
 */
export function medianFocus(values: (number | null)[]): number | null {
  const hits = values
    .filter((v): v is number => v !== null && Number.isFinite(v))
    .sort((a, b) => a - b);
  if (hits.length === 0) return null;
  const mid = Math.floor(hits.length / 2);
  return hits.length % 2 === 1 ? hits[mid] : (hits[mid - 1] + hits[mid]) / 2;
}

/**
 * The `x` argument for ffmpeg's crop filter, panning the window so `focusX` lands in the
 * middle of it.
 *
 * Written as an ffmpeg EXPRESSION rather than a number on purpose: the crop runs after a
 * cover-scale, so the width it operates on is decided inside the filtergraph and is not known
 * here without a second probe. `in_w` / `out_w` are evaluated by ffmpeg at that point, which
 * also means this stays correct if the canvas or the source resolution changes.
 *
 * Ideal left edge is `focusX*in_w - out_w/2`; the clamp keeps the window inside the frame, so
 * a face near either edge yields an edge-aligned panel rather than black bars. Commas inside a
 * filter argument have to be escaped or the filtergraph parser reads them as filter separators.
 *
 * Returns null for a null focus — the caller then omits `x` entirely and ffmpeg's own default
 * centres it, keeping the pre-existing arg string byte-identical.
 *
 * Pure — unit-tested.
 */
export function focusCropX(focusX: number | null): string | null {
  if (focusX === null || !Number.isFinite(focusX)) return null;
  const f = Math.min(1, Math.max(0, focusX));
  // Already centred to within a pixel or two of the default — don't perturb the args.
  if (Math.abs(f - 0.5) < 0.01) return null;
  return `max(0\\,min(in_w-out_w\\,in_w*${f.toFixed(4)}-out_w/2))`;
}

/**
 * The crop window `focusCropX` will produce, in FRACTIONS of the source width — the same
 * clamp, done in JS so a frame can be cropped with sharp exactly the way ffmpeg will crop the
 * clip. `panelFrac` is the panel's width as a fraction of the cover-scaled source width (see
 * `panelFraction`); ≥ 1 means no horizontal slack, the whole frame shows and the window is
 * the whole frame.
 *
 * Pure — unit-tested.
 */
export function cropWindow(
  focusX: number | null,
  panelFrac: number
): { left: number; width: number } {
  if (!(panelFrac > 0) || panelFrac >= 1) return { left: 0, width: 1 };
  const f = focusX == null || !Number.isFinite(focusX) ? 0.5 : focusX;
  const left = Math.min(1 - panelFrac, Math.max(0, f - panelFrac / 2));
  return { left, width: panelFrac };
}

/**
 * How much of the cover-scaled host source the panel shows, as a fraction of its width. The
 * source (`srcW×srcH`) is scaled to the panel height and then `panelW` is cropped from it, so
 * the visible fraction is `panelW / (srcW * panelH / srcH)`. On the stock layout that is
 * 840 / 1920 = 0.4375 for a 16:9 host clip. Pure — unit-tested.
 */
export function panelFraction(
  srcW: number,
  srcH: number,
  panelW: number,
  panelH: number
): number {
  if (!(srcW > 0) || !(srcH > 0) || !(panelW > 0) || !(panelH > 0)) return 1;
  return panelW / ((srcW * panelH) / srcH);
}

/**
 * Where a face at `faceX` (fraction of the source) lands inside the panel cropped around
 * `focusX`, as a fraction of the panel width (0.5 = dead centre). Pure — unit-tested.
 */
export function faceInPanel(
  faceX: number,
  focusX: number | null,
  panelFrac: number
): number {
  const w = cropWindow(focusX, panelFrac);
  return (faceX - w.left) / w.width;
}

/**
 * Correct a focus by an observed panel error: the face was seen at `observedPanelX` of the
 * panel (0.5 is the goal), so shift the focus by that error converted back into source
 * fractions. Clamped to 0..1. Pure — unit-tested.
 */
export function correctFocus(
  focusX: number,
  observedPanelX: number,
  panelFrac: number
): number {
  const err = observedPanelX - 0.5;
  return Math.min(1, Math.max(0, focusX + err * panelFrac));
}

/** Deterministic detector: pico on a downscaled grayscale copy. Null when no face clears `minQ`. */
async function picoFaceCenterX(buffer: Buffer): Promise<number | null> {
  const { data, info } = await sharp(buffer)
    .resize({ width: FACE_SCAN_WIDTH, withoutEnlargement: true })
    .grayscale()
    .raw()
    .toBuffer({ resolveWithObject: true });
  if (info.channels !== 1) return null;
  const faces = detectFaces(
    new Uint8Array(data.buffer, data.byteOffset, data.byteLength),
    info.width,
    info.height
  );
  if (!faces.length) return null;
  return faces[0].x / info.width;
}

/** LLM detector: the fallback for faces the cascade cannot see. Null on any failure. */
async function haikuFaceCenterX(buffer: Buffer): Promise<number | null> {
  const small = await sharp(buffer)
    .resize({ width: 512, withoutEnlargement: true })
    .png()
    .toBuffer();
  const image: ClaudeImage = {
    base64: small.toString("base64"),
    mediaType: "image/png",
  };
  const result = await invokeClaude({
    systemPrompt: FACE_ALIGN_SYSTEM,
    userMessage: "Where is the face horizontally in this frame?",
    imageInput: image,
    maxTokens: 64,
    model: FACE_ALIGN_MODEL,
  });
  return parseFaceCenter(result.text, result.stopReason);
}

/**
 * Horizontal centre of the face in this frame as a 0..1 fraction plus which detector found
 * it, or null when it cannot be determined. Fails open (null ⇒ centred crop) on every error.
 *
 * `allowHaiku: false` restricts it to the deterministic detector — used by the verify pass,
 * which wants a measurement it can trust, not a second opinion from a coarse ruler.
 *
 * Takes no mimeType: sharp sniffs the format from the bytes and re-encodes, so the declared
 * media type cannot drift from what is actually sent.
 */
export async function detectFace(
  buffer: Buffer,
  opts: { allowHaiku?: boolean } = {}
): Promise<{ x: number; source: FaceSource } | null> {
  try {
    const x = await picoFaceCenterX(buffer);
    if (x !== null) return { x, source: "pico" };
  } catch (err: any) {
    console.warn(`[FaceAlign] pico detection failed: ${err.message}`);
  }
  if (opts.allowHaiku === false) return null;
  try {
    const x = await haikuFaceCenterX(buffer);
    if (x !== null) return { x, source: "haiku" };
  } catch (err: any) {
    // Fail open. Nothing downstream catches this, so the warn is the only trace; the split
    // renders with the old centred crop.
    console.warn(
      `[FaceAlign] haiku detection failed: ${err.message} — centring the host panel`
    );
  }
  return null;
}

/** Back-compat shape of `detectFace`: just the fraction. */
export async function detectFaceCenterX(
  buffer: Buffer
): Promise<number | null> {
  return (await detectFace(buffer))?.x ?? null;
}
