/**
 * server/faceAlign.ts
 *
 * Where the host's face sits in a frame, so the split-screen crop can keep it.
 *
 * The split-screen host panel is the CANVAS REMAINDER, not a half: on 1920x1080 the b-roll
 * takes a square 1080 panel and the host gets 840. `buildSplitScreenArgs` cover-scales the
 * 1920x1080 lip-synced clip to fill that panel — which is a no-op, both are 1080 tall — and
 * then crops 840 wide. With no x that crop is CENTRED, so the panel is the middle 43.75% of
 * the source frame and everything outside it is discarded.
 *
 * That is fine only while the face is centred in the source. It frequently is not: the host
 * plate is generated by an image model from a photo reference (`hostPlate.ts`), and the model
 * frames the subject wherever it likes — off to one side, at the edge of the frame. The
 * lip-sync provider animates whatever it is handed, so an off-centre plate becomes an
 * off-centre clip, and the centred crop then pushes the face against the divider or slices it.
 *
 * So: look at one frame, ask where the face is, and pan the crop window to put it in the
 * middle of the panel.
 *
 * NEVER THROWS. Every failure path — no key, a 529, an unparseable answer, no face in frame —
 * returns null, and null means "crop centred", which is exactly the behaviour that existed
 * before this module. A dead detector costs alignment, never a render.
 */
import sharp from "sharp";
import { invokeClaude, type ClaudeImage } from "./claude";
import { safeParseJSON } from "./jsonRepair";

/**
 * Haiku, for the same reason `overlayTextScan.ts` uses it: `invokeClaude` sends no `thinking`
 * param on its non-thinking branch, and on sonnet-5 that means ADAPTIVE THINKING — seconds of
 * reasoning per call, on the render's critical path, to locate a face. Haiku 4.5 predates
 * adaptive thinking, so this is a plain fast completion.
 */
const FACE_ALIGN_MODEL = "claude-haiku-4-5-20251001";

/**
 * Downscale before the call. Vision tokens are ~(w*h)/750, so the pixels dominate the cost of a
 * call this small. 512 wide is far more than enough to say WHERE a face is — this is not
 * reading an expression, it is locating a head-sized region.
 */
const FACE_SCAN_WIDTH = 512;

const FACE_ALIGN_SYSTEM =
  "You are given ONE frame from a talking-head video. Locate the main person's FACE and " +
  "report its horizontal centre as a fraction of the image width.\n\n" +
  "0.0 is the very left edge of the image, 0.5 is the exact horizontal middle, 1.0 is the " +
  "very right edge. Measure to the centre of the FACE — between the eyes — not to the centre " +
  "of the body, the shoulders, or the hair.\n\n" +
  "If several people are visible, use the largest, most in-focus, most central face — the one " +
  "the shot is of. If no human face is visible at all, say so instead of guessing.\n\n" +
  'Return ONLY this JSON, no prose: {"found":true|false,"x":0.00}\n' +
  "x: the fraction, 2 decimal places. Use 0.5 when found is false.";

/**
 * Read a verdict into a horizontal fraction, or null when there is nothing usable.
 *
 * Null on anything off-shape, out of range, or not-found. The caller treats null as "leave the
 * crop centred", so a garbled answer must reach null rather than a plausible-looking number —
 * a confidently wrong 0.9 would pan the face straight out of the panel, which is worse than
 * the miscentring this module exists to fix.
 *
 * Pure — unit-tested.
 */
export function parseFaceCenter(
  raw: string,
  stopReason?: string
): number | null {
  const parsed = safeParseJSON<any>(raw, stopReason);
  if (!parsed.success) return null;
  if (parsed.data?.found !== true) return null;
  const x = parsed.data.x;
  if (typeof x !== "number" || !Number.isFinite(x)) return null;
  if (x < 0 || x > 1) return null;
  return x;
}

/**
 * The `x` argument for ffmpeg's crop filter, panning the window so `focusX` lands in the
 * middle of it.
 *
 * Written as an ffmpeg EXPRESSION rather than a number on purpose: the crop runs after a
 * cover-scale, so the width it operates on is decided inside the filtergraph and is not known
 * here without a second probe. `in_w` / `out_w` are evaluated by ffmpeg at that point, which
 * also means this stays correct if the canvas or the source resolution changes.
 *
 * Ideal left edge is `focusX*in_w - out_w/2`; the clamp keeps the window inside the frame, so
 * a face near either edge yields an edge-aligned panel rather than black bars. Commas inside a
 * filter argument have to be escaped or the filtergraph parser reads them as filter separators.
 *
 * Returns null for a null focus — the caller then omits `x` entirely and ffmpeg's own default
 * centres it, keeping the pre-existing arg string byte-identical.
 *
 * Pure — unit-tested.
 */
export function focusCropX(focusX: number | null): string | null {
  if (focusX === null || !Number.isFinite(focusX)) return null;
  const f = Math.min(1, Math.max(0, focusX));
  // Already centred to within a pixel or two of the default — don't perturb the args.
  if (Math.abs(f - 0.5) < 0.01) return null;
  return `max(0\\,min(in_w-out_w\\,in_w*${f.toFixed(4)}-out_w/2))`;
}

/**
 * Horizontal centre of the face in this frame as a 0..1 fraction, or null when it cannot be
 * determined. Fails open (null ⇒ centred crop) on every error.
 *
 * Takes no mimeType: sharp sniffs the format from the bytes and re-encodes png, so the declared
 * media type cannot drift from what is actually sent.
 */
export async function detectFaceCenterX(
  buffer: Buffer
): Promise<number | null> {
  try {
    const small = await sharp(buffer)
      .resize({ width: FACE_SCAN_WIDTH, withoutEnlargement: true })
      .png()
      .toBuffer();
    const image: ClaudeImage = {
      base64: small.toString("base64"),
      mediaType: "image/png",
    };
    const result = await invokeClaude({
      systemPrompt: FACE_ALIGN_SYSTEM,
      userMessage: "Where is the face horizontally in this frame?",
      imageInput: image,
      maxTokens: 64,
      model: FACE_ALIGN_MODEL,
    });
    return parseFaceCenter(result.text, result.stopReason);
  } catch (err: any) {
    // Fail open. Nothing downstream catches this, so the warn is the only trace; the split
    // renders with the old centred crop.
    console.warn(
      `[FaceAlign] detection failed: ${err.message} — centring the host panel`
    );
    return null;
  }
}
