import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  BookOpen,
  ImageIcon,
  Loader2,
  QrCode,
  Trash2,
  CheckCircle2,
  AlertTriangle,
} from "lucide-react";
import { toast } from "sonner";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

/**
 * A channel's BOOKS — the products its videos pitch — edited inside the channel it belongs to.
 *
 * A book carries the cover its CTA reveals and the shop link its QR encodes. The shop link is the
 * load-bearing field: the per-video tracking link is that URL plus `?ref=<video>`, so a book
 * without one still appears on screen but earns no attribution.
 *
 * Books are per channel and never shared, so the same title sold on two channels is two rows and
 * their sales stay separable. That is exactly why this lives in the channel editor rather than a
 * standalone Admin tab: the channel is already the unit being configured, so its books belong
 * beside its host photo and voice instead of behind a second channel picker somewhere else.
 *
 * `channelKey` is supplied by the editor, so there is no channel selector here — the channel on
 * screen IS the scope.
 */

const ACCEPTED = ["image/jpeg", "image/png", "image/webp"];

type Draft = {
  id?: number;
  title: string;
  coverImageUrl: string;
  shopUrl: string;
};

const EMPTY: Draft = { title: "", coverImageUrl: "", shopUrl: "" };

/** Sentinel for "no video picked" — a Select value may not be an empty string. */
const NO_VIDEO = "__none__";

/** Cover upload — same flow as the channel assets. */
function CoverPicker({
  value,
  onChange,
  disabled,
}: {
  value: string;
  onChange: (url: string) => void;
  disabled?: boolean;
}) {
  const upload = trpc.styleReference.upload.useMutation({
    onSuccess: ({ url }) => onChange(url),
    onError: err => toast.error(err.message),
  });
  if (value) {
    return (
      <div className="flex items-center gap-3">
        <img
          src={value}
          alt="Cover"
          className="h-20 w-16 rounded border border-border object-cover"
        />
        <Button
          variant="outline"
          size="sm"
          className="h-7 text-xs"
          disabled={disabled}
          onClick={() => onChange("")}
        >
          Remove
        </Button>
      </div>
    );
  }
  return (
    <label className="inline-flex h-8 cursor-pointer items-center gap-2 rounded-md border border-dashed border-border bg-secondary/30 px-3 text-xs text-muted-foreground hover:bg-secondary/50 hover:text-foreground">
      {upload.isPending ? (
        <Loader2 className="h-4 w-4 animate-spin" />
      ) : (
        <ImageIcon className="h-4 w-4" />
      )}
      {upload.isPending ? "Uploading…" : "Upload cover"}
      <input
        type="file"
        accept={ACCEPTED.join(",")}
        className="hidden"
        disabled={disabled || upload.isPending}
        onChange={e => {
          const file = e.target.files?.[0];
          e.target.value = "";
          if (!file) return;
          if (!ACCEPTED.includes(file.type))
            return toast.error("Use a JPG, PNG, or WEBP image.");
          if (file.size > 10 * 1024 * 1024)
            return toast.error("Image must be under 10 MB");
          const reader = new FileReader();
          reader.onload = () =>
            upload.mutate({ dataUrl: reader.result as string });
          reader.readAsDataURL(file);
        }}
      />
    </label>
  );
}

/**
 * The book's plain QR (no video tag), so the operator can confirm the link is right BEFORE any
 * render. The preview is generated by the same code the pipeline uses and is decoded back
 * server-side, so "it looks like a QR" is never mistaken for "it scans".
 */
function QrPreview({
  shopUrl,
  bookId,
  channelKey,
}: {
  shopUrl: string;
  bookId?: number;
  channelKey: string;
}) {
  const [show, setShow] = useState(false);
  const [pick, setPick] = useState<string>(NO_VIDEO);

  // Real videos on this channel. A book carries no tag of its own — the tag identifies a VIDEO —
  // so the only honest way to show a tracking link is against an actual one.
  const { data: videos } = trpc.book.videosForBook.useQuery(
    { channelKey, bookId },
    { enabled: show && !!channelKey }
  );
  const chosen = (videos ?? []).find(v => String(v.id) === pick);

  // A video that REALLY pitched this book already has its link and QR generated and stored —
  // show those, not a re-derivation. Anything else is previewed.
  const isPublished = !!chosen?.usedThisBook && !!chosen.trackingUrl;
  const { data, isLoading, error } = trpc.book.previewQr.useQuery(
    { shopUrl, jobId: chosen ? chosen.id : undefined },
    { enabled: show && shopUrl.trim().length > 0 && !isPublished }
  );

  if (!shopUrl.trim()) return null;
  if (!show) {
    return (
      <Button
        variant="outline"
        size="sm"
        className="h-7 text-xs"
        onClick={() => setShow(true)}
      >
        <QrCode className="mr-1.5 h-3.5 w-3.5" />
        Preview QR
      </Button>
    );
  }

  const shownUrl = isPublished ? chosen!.trackingUrl! : data?.url;
  const shownQr = isPublished ? chosen!.qrImageUrl! : data?.dataUrl;

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap items-center gap-2">
        <Label className="text-[11px] text-muted-foreground">
          Show link for
        </Label>
        <Select value={pick} onValueChange={setPick}>
          <SelectTrigger className="h-7 w-full max-w-64 text-xs">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value={NO_VIDEO}>
              No video — the plain shop link
            </SelectItem>
            {(videos ?? []).map(v => (
              <SelectItem key={v.id} value={String(v.id)}>
                #{v.id} · {v.title ?? "(untitled)"}
                {v.usedThisBook ? "  ✓ uses this book" : ""}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        {videos && videos.length === 0 && (
          <span className="text-[11px] text-muted-foreground">
            no videos on this channel yet
          </span>
        )}
      </div>

      {isLoading && !isPublished ? (
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating…
        </div>
      ) : error && !isPublished ? (
        <p className="text-xs text-destructive">{error.message}</p>
      ) : (
        <div className="flex flex-wrap items-start gap-3">
          <img
            src={shownQr}
            alt="QR"
            className="h-24 w-24 shrink-0 rounded border border-border bg-white"
          />
          <div className="min-w-0 flex-1 space-y-1 text-xs">
            {isPublished ? (
              <p className="flex items-center gap-1.5 text-success">
                <CheckCircle2 className="h-3.5 w-3.5" />
                This is the real code from video #{chosen!.id}
              </p>
            ) : data?.verified ? (
              <p className="flex items-center gap-1.5 text-success">
                <CheckCircle2 className="h-3.5 w-3.5" />
                Scans correctly
              </p>
            ) : (
              <p className="flex items-center gap-1.5 text-warning">
                <AlertTriangle className="h-3.5 w-3.5" />
                Could not be read back
              </p>
            )}
            <p className="break-all text-muted-foreground">{shownUrl}</p>
            {chosen ? (
              <>
                <p className="text-muted-foreground">
                  {isPublished
                    ? "Generated when that video rendered — this is what is on screen and in its description."
                    : `What video #${chosen.id} would show, if it pitched this book.`}
                </p>
                {shownUrl && (
                  <a
                    href={shownUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-block underline underline-offset-2"
                  >
                    Open it →
                  </a>
                )}
              </>
            ) : (
              <p className="text-muted-foreground">
                The book&apos;s own link — no tag. Pick a video above to see a
                real tracking link.
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export function ChannelBooks({ channelKey }: { channelKey: string }) {
  const utils = trpc.useUtils();
  const [draft, setDraft] = useState<Draft>(EMPTY);
  const [pendingDelete, setPendingDelete] = useState<Draft & { id: number } | null>(
    null
  );

  // Removed books are soft-deleted server-side (videos that already used one still resolve it
  // by id), but this list has no undelete — so it only ever shows the live ones.
  const { data: books, isLoading } = trpc.book.list.useQuery(
    { channelKey, activeOnly: true },
    { enabled: !!channelKey }
  );

  const save = trpc.book.save.useMutation({
    onSuccess: () => {
      toast.success(draft.id ? "Book updated." : "Book added.");
      setDraft(EMPTY);
      utils.book.list.invalidate();
    },
    onError: err => toast.error(err.message),
  });

  const remove = trpc.book.deactivate.useMutation({
    onSuccess: () => {
      toast.success(
        "Book removed — videos that already used it are unaffected."
      );
      setPendingDelete(null);
      utils.book.list.invalidate();
    },
    onError: err => toast.error(err.message),
  });

  const canSave = !!channelKey && draft.title.trim().length > 0;

  return (
    <div className="space-y-3">
      <div>
        <Label className="flex items-center gap-1.5 text-xs">
          <BookOpen className="h-3.5 w-3.5" />
          Books
        </Label>
        <p className="mt-1 text-[11px] text-muted-foreground">
          The products this channel&apos;s videos pitch. Each book has its own
          cover and its own shop link — a video can pitch a different book in
          its mid-roll and its close. The shop link is what makes sales
          traceable: every video appends its own tag to it, and its on-screen QR
          encodes that.
        </p>
        {/* The channel fields above are staged and written by Save Configuration; these are
            their own rows and are written the moment you press Add/Save/Remove. Saying so
            avoids the reasonable assumption that a book is lost unless you also save the
            channel. */}
        <p className="mt-1 text-[11px] italic text-muted-foreground">
          Books save on their own — Save Configuration below covers the channel
          fields, not this list.
        </p>
      </div>

      {isLoading ? (
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" /> Loading…
        </div>
      ) : (books ?? []).length === 0 ? (
        <p className="text-[11px] italic text-muted-foreground">
          No books yet. Add the first below.
        </p>
      ) : (
        <div className="space-y-2">
          {(books ?? []).map(b => (
            <div key={b.id} className="rounded-md border border-border p-3">
              <div className="flex flex-wrap items-start gap-3">
                {b.coverImageUrl ? (
                  <img
                    src={b.coverImageUrl}
                    alt=""
                    className="h-16 w-12 shrink-0 rounded border border-border object-cover"
                  />
                ) : (
                  <div className="flex h-16 w-12 shrink-0 items-center justify-center rounded border border-dashed border-border">
                    <BookOpen className="h-4 w-4 text-muted-foreground" />
                  </div>
                )}
                <div className="min-w-0 flex-1">
                  <div className="truncate text-sm font-medium">
                    {b.title}
                  </div>
                  <div className="truncate text-xs text-muted-foreground">
                    {b.shopUrl || (
                      <span className="text-warning">
                        No shop link — this book&apos;s pitch carries no QR and
                        no tracking
                      </span>
                    )}
                  </div>
                </div>
                <div className="flex shrink-0 gap-1">
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-7 text-xs"
                    onClick={() =>
                      setDraft({
                        id: b.id,
                        title: b.title,
                        coverImageUrl: b.coverImageUrl ?? "",
                        shopUrl: b.shopUrl ?? "",
                      })
                    }
                  >
                    Edit
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-7 w-7 p-0"
                    aria-label={`Remove ${b.title}`}
                    onClick={() =>
                      setPendingDelete({
                        id: b.id,
                        title: b.title,
                        coverImageUrl: b.coverImageUrl ?? "",
                        shopUrl: b.shopUrl ?? "",
                      })
                    }
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </div>
              </div>
              {b.shopUrl && (
                <div className="mt-2">
                  <QrPreview
                    shopUrl={b.shopUrl}
                    bookId={b.id}
                    channelKey={channelKey}
                  />
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      <div className="space-y-3 rounded-lg border border-border p-4">
        <div className="text-sm font-medium">
          {draft.id ? "Edit book" : "Add a book"}
        </div>
        <div className="space-y-1.5">
          <Label className="text-xs">Title</Label>
          <Input
            value={draft.title}
            onChange={e => setDraft(d => ({ ...d, title: e.target.value }))}
            placeholder="The Backyard Soil Handbook"
            className="h-8 text-xs"
          />
          <p className="text-[11px] text-muted-foreground">
            Also what the pipeline listens for in the pitch, to place the cover
            reveal on the line that names it.
          </p>
        </div>
        <div className="space-y-1.5">
          <Label className="text-xs">Shop link</Label>
          <Input
            value={draft.shopUrl}
            onChange={e => setDraft(d => ({ ...d, shopUrl: e.target.value }))}
            placeholder="https://yourshop.com/the-backyard-soil-handbook"
            className="h-8 text-xs"
          />
          <p className="text-[11px] text-muted-foreground">
            Where this book is sold. Leave the tracking tag off — each video
            adds its own.
          </p>
        </div>
        <div className="space-y-1.5">
          <Label className="text-xs">Cover</Label>
          <CoverPicker
            value={draft.coverImageUrl}
            onChange={url => setDraft(d => ({ ...d, coverImageUrl: url }))}
            disabled={save.isPending}
          />
        </div>
        <div className="flex flex-wrap justify-end gap-2">
          {draft.id && (
            <Button size="sm" variant="outline" onClick={() => setDraft(EMPTY)}>
              Cancel
            </Button>
          )}
          <Button
            size="sm"
            disabled={!canSave || save.isPending}
            onClick={() =>
              save.mutate({
                id: draft.id,
                channelKey,
                title: draft.title,
                coverImageUrl: draft.coverImageUrl || null,
                shopUrl: draft.shopUrl || null,
              })
            }
          >
            {save.isPending
              ? "Saving…"
              : draft.id
                ? "Save changes"
                : "Add book"}
          </Button>
        </div>
      </div>

      <AlertDialog
        open={pendingDelete !== null}
        onOpenChange={open => {
          if (!open && !remove.isPending) setPendingDelete(null);
        }}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Remove {pendingDelete?.title}?</AlertDialogTitle>
            <AlertDialogDescription>
              This removes the book from this channel&apos;s list — it can no
              longer be pitched in new videos. Videos that already used it keep
              their sales history and are unaffected. This can&apos;t be undone
              from here.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={remove.isPending}>
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={e => {
                e.preventDefault();
                if (pendingDelete) remove.mutate({ id: pendingDelete.id });
              }}
              disabled={remove.isPending}
              className="bg-destructive hover:bg-destructive/90"
            >
              {remove.isPending ? (
                <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" />
              ) : null}
              Remove
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
