import { describe, expect, it } from "vitest";
import { currentTake, refreshActiveTake } from "./hostTakes";
import {
  activePictureTakeIndex,
  currentPicture,
  pictureTakeLabel,
  recordRegeneratedPicture,
  sceneVersionCount,
  selectPictureTake,
} from "./pictureTakes";
import type { StoryboardScene } from "./types";

const scene = (over: Partial<StoryboardScene> = {}): StoryboardScene =>
  ({
    index: 7,
    narration: "a line",
    visualPrompt: "a basket of scraps",
    clipUrls: ["old.mp4"],
    clipUrl: "old.mp4",
    ...over,
  }) as StoryboardScene;

const regenerate = (s: StoryboardScene, clip: string, prompt: string) => {
  const before = currentPicture(
    s,
    s.pictureTakes?.length ? "regenerate" : "original"
  );
  s.clipUrls = [clip];
  s.clipUrl = clip;
  s.visualPrompt = prompt;
  recordRegeneratedPicture(s, before, { id: 2, name: "Hank" });
};

describe("picture takes", () => {
  it("a regenerate keeps the picture it replaced, with the new one showing", () => {
    const s = scene();
    regenerate(s, "new.mp4", "a folded quilt");
    expect(s.pictureTakes?.map(t => t.clipUrl)).toEqual(["old.mp4", "new.mp4"]);
    expect(activePictureTakeIndex(s)).toBe(1);
    expect(pictureTakeLabel(s.pictureTakes![0], 0)).toBe("Picture 1 (original)");
    expect(pictureTakeLabel(s.pictureTakes![1], 1)).toBe(
      "Picture 2 (regenerated by Hank)"
    );
  });

  it("switching back restores the old clip and the description it was drawn from", () => {
    const s = scene();
    regenerate(s, "new.mp4", "a folded quilt");
    expect(selectPictureTake(s, 0)).toEqual({ ok: true, changed: true });
    expect(s).toMatchObject({
      clipUrl: "old.mp4",
      clipUrls: ["old.mp4"],
      visualPrompt: "a basket of scraps",
      activePictureTake: 0,
    });
    expect(selectPictureTake(s, 1)).toEqual({ ok: true, changed: true });
    expect(s.visualPrompt).toBe("a folded quilt");
  });

  it("a second regenerate adds a third picture and never repeats one", () => {
    const s = scene();
    regenerate(s, "new1.mp4", "one");
    regenerate(s, "new2.mp4", "two");
    expect(s.pictureTakes?.map(t => t.clipUrl)).toEqual([
      "old.mp4",
      "new1.mp4",
      "new2.mp4",
    ]);
  });

  it("starts no list for a scene that had no picture", () => {
    const s = scene({ clipUrls: [], clipUrl: undefined });
    regenerate(s, "first.mp4", "one");
    expect(s.pictureTakes).toBeUndefined();
  });

  it("refuses a picture that does not exist, and a scene that became a host scene", () => {
    expect(selectPictureTake(scene(), 0).ok).toBe(false);
    const s = scene();
    regenerate(s, "new.mp4", "two");
    expect(selectPictureTake(s, 9).ok).toBe(false);
    expect(selectPictureTake(s, 1)).toEqual({ ok: true, changed: false });
    s.hostPresent = true;
    expect(selectPictureTake(s, 0).ok).toBe(false);
  });
});

describe("the Versions button", () => {
  it("is not shown for a scene with nothing to switch between", () => {
    expect(sceneVersionCount(scene())).toBe(0);
  });

  it("counts a cutaway's pictures or voices, whichever is more", () => {
    const s = scene();
    regenerate(s, "new.mp4", "two");
    expect(sceneVersionCount(s)).toBe(2);
    s.voiceTakes = [
      { audioUrl: "a.mp3", at: "", source: "original" },
      { audioUrl: "b.mp3", at: "", source: "redo" },
      { audioUrl: "c.mp3", at: "", source: "redo" },
    ];
    expect(sceneVersionCount(s)).toBe(3);
  });

  it("counts a host scene's takes only", () => {
    const s = scene({ hostPresent: true });
    expect(sceneVersionCount(s)).toBe(0);
    s.hostTakes = [
      { clipUrls: ["a.mp4"], at: "", source: "original" },
      { clipUrls: ["b.mp4"], at: "", source: "regenerate" },
    ];
    expect(sceneVersionCount(s)).toBe(2);
  });
});

describe("a split screen whose panel is redrawn", () => {
  it("brings the take it is showing up to date, leaving the other one alone", () => {
    const s = scene({
      hostPresent: true,
      splitVisual: "a still",
      clipUrls: ["composite-2.mp4"],
      clipUrl: "composite-2.mp4",
      hostClipUrls: ["host-2.mp4"],
    });
    s.hostTakes = [
      { clipUrls: ["composite-1.mp4"], at: "t0", source: "original" },
      currentTake(s, "regenerate", undefined, "t1")!,
    ];
    s.activeTake = 1;
    s.clipUrls = ["composite-2b.mp4"];
    s.clipUrl = "composite-2b.mp4";
    refreshActiveTake(s);
    expect(s.hostTakes.map(t => t.clipUrls[0])).toEqual([
      "composite-1.mp4",
      "composite-2b.mp4",
    ]);
    expect(s.hostTakes[1]).toMatchObject({ at: "t1", source: "regenerate" });
  });

  it("does nothing on a beat with no takes", () => {
    const s = scene({ hostPresent: true });
    refreshActiveTake(s);
    expect(s.hostTakes).toBeUndefined();
  });
});
