/**
 * Picture TAKES — the old and the new picture of a regenerated CUTAWAY (a still or a b-roll clip).
 *
 * A regenerate used to throw away the picture it replaced, so a new one that came back worse
 * could only be fixed by paying for another. The picture a cutaway had is now kept beside the new
 * one; the new one shows by default and the operator can put the old one back for free —
 * switching is a metadata write and both clips stay on R2. Mirrors `shared/hostTakes.ts`, which
 * does the same for a host beat (whose take also carries its voice).
 *
 * Pure and shared: the edit session records and swaps takes, the Versions box lists them, the
 * tests pin the rules.
 */
import type { PictureTake, StoryboardScene, SubmitActor } from "./types";

/** The cutaway's current picture as a take, or null when it has no clip to keep. */
export function currentPicture(
  scene: StoryboardScene,
  source: PictureTake["source"],
  by?: SubmitActor,
  at = new Date().toISOString()
): PictureTake | null {
  const clipUrls = scene.clipUrls?.length
    ? [...scene.clipUrls]
    : scene.clipUrl
      ? [scene.clipUrl]
      : [];
  if (!clipUrls.length) return null;
  const take: PictureTake = { clipUrls, at, source };
  if (scene.clipUrl) take.clipUrl = scene.clipUrl;
  if (scene.clipShortSec != null) take.clipShortSec = scene.clipShortSec;
  if (scene.visualPrompt) take.visualPrompt = scene.visualPrompt;
  if (by) take.by = by;
  return take;
}

/** Put a take's picture on the scene. */
export function applyPicture(scene: StoryboardScene, take: PictureTake): void {
  scene.clipUrls = [...take.clipUrls];
  scene.clipUrl = take.clipUrl ?? take.clipUrls[0];
  scene.clipShortSec = take.clipShortSec;
  if (take.visualPrompt) scene.visualPrompt = take.visualPrompt;
}

const sameClip = (a: PictureTake, b: PictureTake) =>
  a.clipUrls.join("|") === b.clipUrls.join("|");

/**
 * After a cutaway regenerate lands: keep `before` (the picture it had) and add the new picture as
 * the next take, which becomes the active one. `before` null ⇒ the scene had no picture, so no
 * take list is started. Idempotent on the same clip.
 */
export function recordRegeneratedPicture(
  scene: StoryboardScene,
  before: PictureTake | null,
  by?: SubmitActor
): void {
  const fresh = currentPicture(scene, "regenerate", by);
  if (!fresh) return;
  const takes = scene.pictureTakes?.length
    ? [...scene.pictureTakes]
    : before
      ? [before]
      : [];
  if (!takes.length) return;
  if (before && !takes.some(t => sameClip(t, before))) takes.push(before);
  const existing = takes.findIndex(t => sameClip(t, fresh));
  if (existing >= 0) {
    scene.pictureTakes = takes;
    scene.activePictureTake = existing;
    return;
  }
  takes.push(fresh);
  scene.pictureTakes = takes;
  scene.activePictureTake = takes.length - 1;
}

/** Index of the picture the scene is showing, or null when it has no take list. */
export function activePictureTakeIndex(scene: StoryboardScene): number | null {
  const takes = scene.pictureTakes;
  if (!takes?.length) return null;
  const i = scene.activePictureTake ?? takes.length - 1;
  return i >= 0 && i < takes.length ? i : takes.length - 1;
}

/**
 * Switch the cutaway to picture take `index`. Returns an error message instead of throwing so
 * the edit session can surface it; a no-op switch (already showing it) is ok.
 */
export function selectPictureTake(
  scene: StoryboardScene,
  index: number
): { ok: true; changed: boolean } | { ok: false; reason: string } {
  const takes = scene.pictureTakes;
  if (!takes?.length)
    return { ok: false, reason: "This scene has only one picture" };
  if (!Number.isInteger(index) || index < 0 || index >= takes.length)
    return { ok: false, reason: `Picture ${index + 1} does not exist` };
  if (scene.hostPresent)
    return {
      ok: false,
      reason: "This scene is a host scene now — its earlier pictures no longer apply",
    };
  if (activePictureTakeIndex(scene) === index)
    return { ok: true, changed: false };
  applyPicture(scene, takes[index]);
  scene.activePictureTake = index;
  return { ok: true, changed: true };
}

/** "Picture 1 (original)", "Picture 2 (regenerated by Hank)". */
export function pictureTakeLabel(take: PictureTake, index: number): string {
  const what =
    take.source === "original"
      ? "original"
      : take.by
        ? `regenerated by ${take.by.name}`
        : "regenerated";
  return `Picture ${index + 1} (${what})`;
}

/**
 * How many versions a scene has to choose between, for the card's "Versions" button: a host
 * beat's takes (clip and voice together), or a cutaway's pictures and voices. 0 ⇒ nothing to
 * switch, and the button is not shown.
 */
export function sceneVersionCount(scene: StoryboardScene): number {
  if (scene.hostPresent) {
    const n = scene.hostTakes?.length ?? 0;
    return n > 1 ? n : 0;
  }
  const pictures = scene.pictureTakes?.length ?? 0;
  const voices = scene.voiceTakes?.length ?? 0;
  return Math.max(pictures > 1 ? pictures : 0, voices > 1 ? voices : 0);
}
